### ISSUE TITLE
message_signing::sigrec_decode panics for 0-length signatures

### ISSUE THREAD

**Issue by sr-gi** [rust-bitcoin/rust-lightning#1005]
If an empty signature is passed to `sigrec_decode`, the function will panic at extracting `rsig` and `rid`.

https://github.com/rust-bitcoin/rust-lightning/blob/1f1d7c6890c6c9bef70eeb4ec4c6841e3344159b/lightning/src/util/message_signing.rs#L38-L40

Given `sigrec_decode` is private, this can either be fixed at `recover_pk` after zbase32 decoding the signature, by making sure its length is at least 2, or at `sigrec_decode` by checking the same.

Something on the lines of the following should do:

```
fn sigrec_decode(sig_rec: Vec<u8>) -> Result<RecoverableSignature, Error> {
    if len(sig_rec) < 2 {
        return Error::InvalidSignature;
    }
```

**Comment by sr-gi** [comment]
I can take care of this if the fix makes sense btw

**Comment by TheBlueMatt** [comment]
That looks good to me, though I suppose you could also go ahead and just check that the signature length is exactly 64 + 1 or so https://docs.rs/secp256k1/0.20.3/src/secp256k1/recovery.rs.html#60-80
