### ISSUE TITLE
How should `ConfirmationTarget` be used?

### ISSUE THREAD

**Issue by jeandudey** [rust-bitcoin/rust-lightning#101]
The bitcoind's `estimatesmartfee` method needs a `conf_target` parameter describing the numbers of blocks the TX should wait, it's the same with btcd's "getinfo" method. Shouldn't `ConfirmationTarget` have a method called to retrieve the number of blocks desired to wait?

**Comment by TheBlueMatt** [comment]
The mappings I currently use are here, though I agree adding more docs (as suggestions, not neccessarily requirements) would be very welcome.
https://github.com/TheBlueMatt/rust-lightning-bitcoinrpc/blob/5b3159d4ed931c56d9f557c7bd06decdaafd55fe/src/chain_monitor.rs#L46
