### ISSUE TITLE
Error message deserialization/handling

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#104]
We currently drop all error messages, which we (a) shouldn't do (we need to log them) and (b) shouldn't do (need to close the channel referenced in the error message).

**Comment by ariard** [comment]
For b) you think about all the HandleError with action: None ?
After #91 I think it should be easy to have macro wrapper to log + return.

**Comment by TheBlueMatt** [comment]
Hmm? for (a) indeed we just need #91 and to log, for (b) we need to pass the message into the ChannelManager and force_close the channel.

**Comment by TheBlueMatt** [comment]
I think we're talking about different things here - I'm referring to receiving an Error message on the wire (message type 17) and noting that we need to do two things with it - log it (blocked on #91) and pass the message into the ChannelManager so that it can close the channel. This is wholly separate (I'd think?) from the HandleError/ErrorAction/Event API mess.

**Comment by TheBlueMatt** [comment]
This was resolved in #131. We also handle Errors we send outbound, but thats #109.
