### ISSUE TITLE
Check for outbound feerate update affordability before sending

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#1041]
Turns out we will try to send feerate updates that we cannot at all afford right now. Val caught it in review at https://github.com/rust-bitcoin/rust-lightning/pull/985#discussion_r687139119 and it seems the chanmon_consistency fuzzer has also found it (or something related).

**Comment by ariard** [comment]
I think you should replicate https://github.com/rust-bitcoin/rust-lightning/pull/985/commits/d3af49e9f07fc28d104f1f1dbcf8e216b65e9f89 to limit outbound fee updates, even if we assume our fee estimator is always more "reasonable" than the counterparty one.

**Comment by TheBlueMatt** [comment]
We could do that (I think a simpler approach would be to limit upwards fee increase to eg 25% per $TIME_PERIOD), but independently, we don't limit it at all and can overrun our own reserve value!

**Comment by ariard** [comment]
> I think a simpler approach would be to limit upwards fee increase to eg 25% per $TIME_PERIOD

Right, though such solution would let `max_dust_htlc_exposure` bypass when real-world fees overflow 25% per $TIME_PERIOD, especially noting that $TIME_PERIOD isn't fixed for HTLC's CLTV
