### ISSUE TITLE
implement mark_node_bad in router.rs

### ISSUE THREAD

**Issue by savil** [rust-bitcoin/rust-lightning#106]
https://github.com/rust-bitcoin/rust-lightning/blob/master/src/ln/router.rs#L356-L364

some questions:

1. which callsite(s) would invoke this function? trying to see how to test it.
2. where should we store the state for marking it bad?
- I'm thinking `struct NodeInfo`. We can add a field that stores a timestamp for when it was marked bad, which will let us calculate the exponential decay. Let me know if you have other thoughts.

cc @TheBlueMatt

**Comment by TheBlueMatt** [comment]
I intended this to be along the lines of #59 but for intermediate hops, ie if we fail to route a payment but can't definitively assign blame we might call that to just avoid routing via nodes that might be at fault, but honestly that's not nearly a sufficiently granular API and should maybe just be dropped in favor of a more general "I succeeded at routing a payment over this Route" "I failed to route a payment over this Route, and the blame is Some(node_id) or None" API so we can track whether nodes may be behaving honestly and add some weighting in get_route.

**Comment by TheBlueMatt** [comment]
Subsumed by #486 and #636.
