### ISSUE TITLE
Closing `fee_range` uses invalid `max` value

### ISSUE THREAD

**Issue by t-bast** [rust-bitcoin/rust-lightning#1071]
Hey,

I've been testing the quick close mechanism with the latest LDK, and there's one (small) incompatibility between eclair and rust-lightning. It's exactly similar to https://github.com/ElementsProject/lightning/pull/4599#issuecomment-870584865. When rust-lightning doesn't care about the upper bound it sets `max_fee_satoshis = 0xffffffffffffffff`.

This is rejected by eclair, because we're strict on what values a `satoshi` field can hold. `0xffffffffffffffff` is bigger than 21 million BTC so we consider it an invalid value. We could relax this but I'd like to avoid it if possible. That happens when rust-lightning is simply accepting a value inside eclair's proposed fee range, so I don't think it's necessary to set this to `0xffffffffffffffff`, you could just return the same `max_fee_satoshis` you received.

WDYT?

**Comment by TheBlueMatt** [comment]
Sure, happy to change it to whatever, though ideally the spec would say that we have to keep it within a range if you're gonna check for it - much more sustainable than opening issues on all the implementations :)

**Comment by t-bast** [comment]
> ideally the spec would say that we have to keep it within a range 

I agree, there's no obvious place in the spec right now where we could require that "all bitcoin amounts sent in LN messages must be <= 21 million btc", but I'll add this before the next spec meeting.

**Comment by rustyrussell** [comment]
Set it to the channel size?

**Comment by TheBlueMatt** [comment]
Patch I hacked up just sets it to the remote balance, cause obviously the full channel balance isn’t spendable either :).
