### ISSUE TITLE
Clarify Where PeerManager::process_events happens in docs

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#1075]
Val mentioned at https://github.com/rust-bitcoin/rust-lightning/pull/1043#discussion_r709358380 that the current docs dont really point out explicitly that users shouldnt need to call process_events directly unless they're not using lightning-net-tokio or one of the other clients provided in our language bindings. We should make sure we cover that.

**Comment by vss96** [comment]
@TheBlueMatt Is this already done? If not I can pick it up.

**Comment by TheBlueMatt** [comment]
No, feel free to work on this.
