### ISSUE TITLE
Rename PaymentFailed event

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#1081]
We really need to rename the PaymentFailed event to indicate that sometimes its just a payment part or htlc that failed, not the full payment. see https://github.com/rust-bitcoin/rust-lightning/pull/1053#discussion_r710744906

**Comment by valentinewallace** [comment]
@jkczyz think we should rename to `HTLCFailed`? I'm not sure if that makes it weird to have an `all_paths_failed` field. I slightly prefer `PaymentPathFailed` for that reason.

**Comment by jkczyz** [comment]
If we go with the HTLC terminology, we could rename `all_paths_failed` to `payment_failed` perhaps. Note that for scoring we'll need an analogous event for success, possibly `HTLCClaimed` or `PaymentPathSucceeded`.

That said, HTLCs are an implementation detail that probably don't need to be exposed, especially given future payments may not use HTLCs. So perhaps the payment path terminology is more appropriate.

**Comment by valentinewallace** [comment]
HTLC does seem a little low-level for an event name, though other lightning impls have "htlc" in their public API, I'm not a huge fan but don't feel too strongly.

Happy to assign myself this issue if there's consensus on `PaymentPathFailed` or similar. I like `PaymentPathSuccess`for the analogous success event

**Comment by valentinewallace** [comment]
Oops

**Comment by valentinewallace** [comment]
@jkczyz For context, is scoring for successful paths going to be in V1? I thought we were starting with just avoiding previously failed routes

**Comment by jkczyz** [comment]
Yeah, I suppose it could wait until V2.
