### ISSUE TITLE
Implementation goals or list of TODOs

### ISSUE THREAD

**Issue by eupn** [rust-bitcoin/rust-lightning#112]
Hello @TheBlueMatt et al., 

Nice project, I really wanna see the LN daemon written in Rust happen and I wondering if there's a some kind of list of long- and short-term goals (or TODOs) for this particular project so new contributors (and me, hopefully) who know Rust and something about Bitcoin/Cryptography/Distributed would put their hands on and make a contribution.

On the first glance it's kinda hard to see what is already implemented and what should be (for example, list of BOLT's and subsequent tasks/challenges that are implemented/done already and what aren't).

**Comment by TheBlueMatt** [comment]
I think with the exception of #58 there is at least a minimal implementation of non-feature parts of all BOLTs (at least when you consider https://github.com/rust-bitcoin/rust-lightning-invoice). There's still a lot of things to go as you can see from the issues list (https://github.com/rust-bitcoin/rust-lightning/issues) but generally I think the issues list doesn't list anything that's already done and has a few "Good first issues" tags. Aside from those, the library still needs some significant stability review passes to make sure the channel logic is robust and spec-compliant, which is the main thrust of effort right now, but the issues list lists most of the high level "projects" that still need done.
Maybe I'm missing what you're asking for?

**Comment by TheBlueMatt** [comment]
Closing as need-more-info, but feel free to ask clarification questions!
