### ISSUE TITLE
Finish ChannelMonitor case handling and add more testing

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#137]
There's one or two TODOs in ChannelMonitor to handle all the listed cases, plus some TODOs in channel-force-close in ChannelManager to update ChannelMonitor, and the test in ChannelManager which construct networks, do various things to them, and then check monitor validity should be fleshed out way way more.

**Comment by ariard** [comment]
Was looking on it, seems to me than for some chain_monitor TODO we need to pass an Arc<ChainWatchInterface> to ChannelMonitor struct and if so, maybe it's make sense to drop it from SimpleManyChannelMonitor?

**Comment by TheBlueMatt** [comment]
I assume you're referring to "TODO: Need to register the given script here with a chain_monitor" and the two "TODO: Register all outputs in commitment_tx with the ChainWatchInterface!"? I'm not 100% sure by what you mean by "drop it from SimpleManyChannelMonitor", though? In any case, yea, not sure if it makes more sense to return such values to the callers (ala the Channel::block_connected telling ChannelManager::block_connected how it should handle it) or if it makes more sense to give it yet another Arc.

**Comment by ariard** [comment]
Yes I'm referring to this ones, I prefer your suggestion with Channel - ChannelManager because I started on the other side and passing ChainWatchInterface means we have to deal with it in channel_monitor serialization/deserialization. Will open a PR soon on this

**Comment by ariard** [comment]
Following BOLT 5 there is a lot of different cases to claim in case of remote node broadcasting a commitment tx.
The Bad Way : 
 - [ ] to_remote outputs via P2WPKH
 - [x] offered htlc outputs via payment preimage tx
 - [x] received htlc outputs via HTLC-timeout tx

The Ugly Way : 
 - [ ] to_remote outputs via P2WPKH (same as above)
 - [ ] to_local outputs via revocation key
 - [ ] offered/received htlc outputs via revocation key
 - [x] HTLC-timeout/HTLC-success outputs via revocation key (with #163)

Seems to me that currently, channel_monitor_network_test currently does only Bad Way 2,3 and Ugly Way 4, do I forget any case ?

**Comment by TheBlueMatt** [comment]
"to_remote outputs via P2WPKH" should be covered by #81 (ie once we have a way for clients to specify the keys they want they should be monitoring the chain for at least the non-derived keys, and obviously documentation should mention this, this also applies to shutdown keys).

The "via revocation key" HTLC outputs are implemented, probably, but aren't tested yet (which you indicated, just being thourough).

The to_local outputs via revocation key I think we impelement? Maybe I'm misunderstanding what the BOLT is referring to, but note that I think we need an interface so that we can tell the client about the availability of an output+the key needed to claim it when we believe the remote side cannot take it (eg its a timelocked output for our latest commitment transaction which we don't think we've ever revoked...we are in no rush to spend it and can let the client do so at their leisure).

**Comment by ariard** [comment]
Yes sorry I checked the code in fact the to_local outputs via revocation is implemented, but seems to me there is not test only for it because in some tests (all?) it's trimmed so it doesn't appear specifically.

#184 is tests for "via revocation key" HTLC outputs, need review. While I was writing tests, I was wandering maybe we could cache tx given to check_spend_remote_tx after 1st pass in case of block re-scanning to avoid generate again same punishment tx.

"to_remote_outputs via P2WPKH", seems fine to be covered by #81, noted.

**Comment by TheBlueMatt** [comment]
I'd hope it doesn't need to get added in ChainWatchInterface, maybe ChannelMonitors should have a different block_connected fn that ChannelManager calls that returns more information and watchtowers (or other calls into ChannelMonitor via ChainWatchInterface) can just ignore the extra data.
The which-object-is-registered-with-ChainWatchInterface stuff is already a mess (see #80) so I don't think rejiggering what calls what is that big a deal right now. Eventually we'll need to rewrite it all and make it harder to misuse but that doesn't need to happen ASAP.

**Comment by ariard** [comment]
Hmm, just a side-not to not forget to add the case of a revoked commitment tx solved by a justice tx, detect it and fail backward.

**Comment by ariard** [comment]
Some notes to check if we have covered everything on on-chain Channel resolution. 

Local Node seeing a Local Commitment Tx : 
- commitment tx  : 

  - to_local output, resolution by output descriptor generated, implemented by [ChannelMonitor::broadcast_by_local_state](https://github.com/rust-bitcoin/rust-lightning/blob/302f1314e5ad33e38d7be000498a670f0e30b183/src/ln/channelmonitor.rs#L1348), tested by test_claim_sizeable_push_msat
  - to_remote output, nothing to be done
  - offered_htlc_output : resolution by HTLC-Timeout tx generated and failure passed backward if needed, implemented by [ChannelMonitor::broadcast_by_local_state](https://github.com/rust-bitcoin/rust-lightning/blob/302f1314e5ad33e38d7be000498a670f0e30b183/src/ln/channelmonitor.rs#L1355), tested by channel_monitor_network_test, test_htlc_on_chain_timeout
  - received_htlc_output : resolution by HTLC-Success tx generated, implemented by [ChannelMonitor::broadcast_by_local_state](https://github.com/rust-bitcoin/rust-lightning/blob/302f1314e5ad33e38d7be000498a670f0e30b183/src/ln/channelmonitor.rs#L1371), tested by channel_monitor_network_test

- HTLC-Timeout tx (from any commitment tx offered_htlc_output) : 
  
  - unique output : resolution by output descriptor generated for unique output, implemented by [ChannelMonitor::broadcast_by_local_state](https://github.com/rust-bitcoin/rust-lightning/blob/302f1314e5ad33e38d7be000498a670f0e30b183/src/ln/channelmonitor.rs#L1368), tested by test_dynamic_spendable_outputs_local_htlc_timeout_tx 

- HTLC-Success tx  (from any commitment tx received_htlc_output) :

  - unique output : resolution by output descriptor generated for unique output, implemented by [ChannelMonitor::broadcast_by_local_state](https://github.com/rust-bitcoin/rust-lightning/blob/302f1314e5ad33e38d7be000498a670f0e30b183/src/ln/channelmonitor.rs#L1384), tested by test_dynamic_spendable_outputs_local_htlc_success_tx

Local Node seeing a Non-Revoked Remote Commitment Tx : 

[WIP]

**Comment by ariard** [comment]
Killed by #336 IMO, not sure if bumping engine is in the scope.

**Comment by TheBlueMatt** [comment]
Nah, I think its fine as-is. I'd like to get better test coverage on it, but this bug itself is probably done.
