### ISSUE TITLE
Handle reconnect/reestablish-existing-Channels

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#138]
This is obviously required for #55 to be useful, but also we have to handle this stuff for simple TCP loss as well.

**Comment by TheBlueMatt** [comment]
Note: to comply with BOLT 7 this must include resending announcement_signatures on reconnect.

**Comment by ariard** [comment]
What's the state of this ? Need to fulfill TODO in peer_connected, L2810 src/ln/channelmanager?

**Comment by TheBlueMatt** [comment]
Yep, thats it. Just need to resend the announcement_signatures for this.

**Comment by ariard** [comment]
Done with #397 I guess
