### ISSUE TITLE
Failure Messages in Onion

### ISSUE THREAD

**Issue by yuntai** [rust-bitcoin/rust-lightning#146]
Additional payloads for some failure codes are not reported back (e.g. `htlc_msat` for `amount_below_minimum`)
And some error checkings are missing - `amount_below_msat`, `expiry_too_soon`, `expiy_too_far` .

**Comment by yuntai** [comment]
I was going thru BOLT 4. I'd like to take it someone else is not working on it.

**Comment by TheBlueMatt** [comment]
I haven't spent any time on it yet so unless someone else chimes in I'd say go for it (and probably want to loop most errors back to the router).

**Comment by ariard** [comment]
Assuming `amount_below_msat` is `fee_insufficient` (no such thing as `amount_below_msat` in the current spec) I think it has been implemented by 4839ef7

**Comment by TheBlueMatt** [comment]
I'm generally a bit dubious of all our htlc-failure-handing crap, but, then, I'm also pretty dubious of the value of the whole thing as a concept, so...OK!
