### ISSUE TITLE
Redo local channel tracking for route generation

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#149]
Currently we require users to interrogate ChannelManager for info on non-public local channels, which makes it particularly hard to comply with BOLT 7 "SHOULD accept channel_updates for its own channels (even if non-public), in order to learn the associated origin nodes' forwarding parameters." I think the obvious solution is to track local channels in Router.

Tagging 0.1 so I can call BOLT 7 completed in #129 "with the exception of other 0.1-tagged issues"

**Comment by ariard** [comment]
Seems to me best is to pass ChannelDetails (or a subset of it) as Event to Router when channels go to ChannelFunded, so Router will handle Event and add what needed to its maps. Maybe can be used to extend network map in the future from others sources than ChannelManager. I'm gonna work on that

**Comment by TheBlueMatt** [comment]
I feel a bit gross passing data back and forth between Router and ChannelManager as events, maybe just duplicate the channel_update message event handling calls to call both/

**Comment by ariard** [comment]
Call both ? Doesn't seems clear to me, how Router is suppose to have access to ChannelManager local channels if it have any reference to it ?

**Comment by TheBlueMatt** [comment]
Sorry, as in add a handle_channel_update fn in ChannelMessageHandler and just have peer_handler call *both* the chan_handler.handle_channel_update and the route_handler.handle_channel_update.

**Comment by TheBlueMatt** [comment]
Effectively fixed in #841.
