### ISSUE TITLE
channel_reserve_satoshis variable names confusing

### ISSUE THREAD

**Issue by yuntai** [rust-bitcoin/rust-lightning#181]
In the spec,
> channel_reserve_satoshis is the minimum amount that the other node is to keep as a direct payment. 

And, as my understanding, this means it's the value that the node receiving Open/AcceptChannel should keep.

We do `channel.thier_channel_reserve_satoshis = msg.channel_reserve_satoshis`
So `channel.their_channel_reserve_satoshis` is used when checking conditions for _our channel reserve_ and I found it pretty confusing.

Perhaps,
`channel.our_channel_reserve_satoshis = msg.channel_reserve_satoshis`
and
`Channel::get_their_channel_reserve_satoshis` is better?

**Comment by TheBlueMatt** [comment]
Hmm, I don't think flipping it on its head is any more clear, it was the value *provided by them* ie its not our own setting, but, indeed, we have to have it towards us. We could rename it something like min_channel_reserve_to_self to make that more clear?

**Comment by yuntai** [comment]
Now I am not confused as you clearly stated, and agree that flipping wouldn't make any clear. I added some comments in #189 and think that would suffice to prevent confusion.

**Comment by valentinewallace** [comment]
Reopening because I'd agree these names are confusing, as pointed out as well by @ariard [here](https://github.com/rust-bitcoin/rust-lightning/pull/577#discussion_r416995828). 

I think it's effectively "our setting," so would be fine to just flip it, but since people seem to disagree I'll go with something along the lines of `remote_channel_reserve_by_us` as suggested by Antoine in the linked comment, or `min_channel_reserve_to_self`

**Comment by jkczyz** [comment]
> Reopening because I'd agree these names are confusing, as pointed out as well by @ariard [here](https://github.com/rust-bitcoin/rust-lightning/pull/577#discussion_r416995828).
> 
> I think it's effectively "our setting," so would be fine to just flip it, but since people seem to disagree I'll go with something along the lines of `remote_channel_reserve_by_us` as suggested by Antoine in the linked comment, or `min_channel_reserve_to_self`

My two sats:

Who is doing the setting is irrelevant once the setting is in place and is thus extraneous information. In the context of a channel, all that matters is what side the reserve applies to. IMHO, "local" and "remote" seem descriptive enough in this case. However, I haven't put much thought into whether there are more suitable names for this concept.
