### ISSUE TITLE
close_channel() API channel_id parameter

### ISSUE THREAD

**Issue by yuntai** [rust-bitcoin/rust-lightning#182]
close_channel() expects channel_id, but channel_id is never reported to the client currently. If user_id is unique for each open_channel(), we can use it instead, but it doesn't apply to the fundee side as the user_id will always be zero. I think we can make another API event, ChannelEstablisehd { user_id, channel_id }.

**Comment by TheBlueMatt** [comment]
You should be able to get the channel_id from ChannelManager::list_channel's return value.
