### ISSUE TITLE
Check commitment transaction fees when testing channel_reserve

### ISSUE THREAD

**Issue by yuntai** [rust-bitcoin/rust-lightning#205]
Currently, the transactions fees are not excluded from the funder's value_to_self_msat before being compared to channel reserve when sending/receiving add_update_fee

Follow up on #189 
See TODO in https://github.com/TheBlueMatt/rust-lightning/commit/1f31e03fac5d451d2cc47a06d681bcd73e4692a2

**Comment by TheBlueMatt** [comment]
Closing assuming we get option_simplified_commitment (#365).
