### ISSUE TITLE
BOLT 2 : SHOULD fail an HTLC which has timed out.

### ISSUE THREAD

**Issue by ariard** [rust-bitcoin/rust-lightning#215]
While reviewing, I had a doubt, where do we implement initiation of our own of removing timeout incoming HTLCs  ? Seems not to be present in any block_connected callbacks right ?

**Comment by TheBlueMatt** [comment]
Indeed, not yet implemented anywhere.

**Comment by SWvheerden** [comment]
#244

**Comment by TheBlueMatt** [comment]
This is basically addressed by #441. Its true that we still may not fail a timed-out htlc when the outbound forwarded leg hasn't yet resolved on-chain, but I think that is the correct behavior.
