### ISSUE TITLE
Investigate dropping Arcs for references

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#237]
We should see if we can take advantage of the borrow checker to drop a bunch of Arcs and hold references in a number of places, may require #80, though. Should also look into nice things like dropping the secp_ctx in Channels and holding a reference to the ChannelManager one, too.

**Comment by TheBlueMatt** [comment]
Oops. We've made great progress here, but there's still a bunch of required Arcs.

**Comment by TheBlueMatt** [comment]
I think we also need a few ChainWatchInterfaces to not be Arcs - at least in Router and SimpleManyChannelMonitor, PeerHandler's Routing and ChannelMessageHandlers should not be Arcs (though I presume that may happen via @arik-so's ongoing work) as well.

**Comment by valentinewallace** [comment]
I realized I'm still assigned to this. @TheBlueMatt are there still TODOs for this issue?

**Comment by TheBlueMatt** [comment]
Hmm, no, likely not. There was some previous discussion to maybe swap the Derefs for `impl Trait for Deref<Target=Trait>` instead, or maybe `BorrowMTarget=Trait>`, but that's separate.
