### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by canndrew** [rust-bitcoin/rust-lightning#343]
I want to start contributing to this project but having to configure my editor to use tabs just when I'm in this project's directory is kind of annoying. No other rust projects use tabs, including rust-bitcoin. In fact no other *projects* use tabs these days. I haven't had to edit code with tabs in it for like, 10 years. Can this project just be normal?

**Edit:** I just noticed there's a .editorconfig file. Still, it means I had to install the editorconfig plugin and means I have to get used to navigating code that has tabs instead of spaces. All for no apparent reason.

**Comment by TheBlueMatt** [comment]
I dunno that no other projects use tabs. Linux kernel still does, last I checked. Anyway, gotta configure your editor for something either way, religious debates aren't really worth it.

**Comment by canndrew** [comment]
I know tabs-vs-spaces is an age-old religious war but I'm pretty sure the war ended years ago and spaces won. I wasn't being *completely* petty opening this either - no other Rust projects have forced me to configure my editor or get used to an annoying-slightly-different way of moving around in code.

But whatevs. You're right that this isn't worth fighting over.
