### ISSUE TITLE
API for regular pings

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#345]
In general, lightning nodes should constantly be pinging their peers to ensure connectivity and ensure that we have a peer marked disconnected before we get a payment to route through them that gets stuck. This will require:
 * Some general API in peer_handler that indicates a timer tick (doesn't have to be that often, just enough to quantize pings and make sure we get pongs back by the next tick).
 * A regular ping generation,
 * Disconnecting a peer if no pong is heard by the next timer tick.

**Comment by ariard** [comment]
@rrybarczyk, this one should be a good first issue if you're looking for something to hack on :)

**Comment by Aleru** [comment]
I would like to implement this and I think there are at least two ways I could do it.

One way is to use the tokio or timer crate, while I know we want to avoid using new dependencies, other files already depend on these. 

The other way would involve using a function pointer in place of the timer tick functionality, so the user of the library would need to pass their own counting utility.

I am wondering if one of these would be preferable or if there is a better way I am not seeing.

**Comment by TheBlueMatt** [comment]
Cool! Might also want to coordinate with @rrybarczyk who was thinking of working on this, I think. As for your question, I don't think you need anything as crazy as a function pointer, just literally a function in the PeerHandler called timer_tick_occurred which the client calls every N seconds (should define N, I assume something like 15-30). The client can schedule it in any way they want.

**Comment by Aleru** [comment]
Sounds good @TheBlueMatt 

As a general rule any advice/revisions from anyone here are graciously accepted :) I am new to open source/software development so this is quite a learning experience and any advice is good advice! 
@rrybarczyk  If your down it would be awesome to work on this w/ you, I am a little bit unsure of the best way to go about coordinating our efforts, but I did create a fork (https://github.com/Aleru/rust-lightning) with an effort at a rough outline of the utilities I think we would need to implement. If indeed you would like to work on this together I was thinking we would work on one of our forks and then push the final changes to master once we are satisfied, perhaps we could also take the conversation to the a fork  (mine is https://github.com/Aleru/rust-lightning).

**Comment by ariard** [comment]
You may be interested by https://bitcointechtalk.com/contributing-to-bitcoin-core-a-personal-account-35f3a594340b, specially having a skim on Pro Git. 
If you don't hear feedback from @rrybarczyk, don't be worry to go forward. And if you any questions you can ask on #rust-bitcoin :)

**Comment by rrybarczyk** [comment]
Hey @aleru, apologies for the delay.

Have you made in progress on this PR? Would definitely like to provided any assistance if needed.

**Comment by Aleru** [comment]
No worries :) your timing is perfect actually as I am running into a bit of an issue
I have a fork that has most of the functionality and two test functions on it https://github.com/Aleru/rust-lightning

you may want to take a look at the fork and of course I am more than happy to answer any questions/ work on solutions.

the current nagging issue i was talking about above is that I have a function called disconnect_if_no_pong(&mut self) It is defined as a method on PeerManager. currently I am not actually able to disconnect the peer from the PeerManager, so the function does not really work.

**Comment by TheBlueMatt** [comment]
Fixed by #437.
