### ISSUE TITLE
Implement Type-Length-Value format

### ISSUE THREAD

**Issue by ariard** [rust-bitcoin/rust-lightning#371]
Now it's merged in 1.1, https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#type-length-value-format (IMO we just need encoding/decoding trait for these ones, have a look in sr/util/ser.rs)

**Comment by TheBlueMatt** [comment]
Note, probably need a framework for these things but may be easier to implement after there are actual uses of them.

**Comment by DR-BoneZ** [comment]
https://crates.io/crates/lightning-wire-msgs

**Comment by TheBlueMatt** [comment]
Closed by #434.
