### ISSUE TITLE
Use lightning-wire-msgs crate?

### ISSUE THREAD

**Issue by dr-bonez** [rust-bitcoin/rust-lightning#376]
I made a [thing](https://crates.io/crates/lightning-wire-msgs).

The purpose of the crate is to implement serialization and deserialization for all lightning wire message types. It is incomplete, however I will be adding many more message types in the coming days. New message types are fairly trivial to add, since I created a set of derive macros to make it very simple and ergonomic.

I created the crate for my own purposes, but I thought it might be useful to the rust lightning project.

If there is interest, I am willing to turn over control of this crate to the rust-bitcoin org.

**Comment by TheBlueMatt** [comment]
That sounds awesome. Mostly just have to make sure it has good test coverage, good fuzz coverage, and doesn't pull in New deps. Did you pull from the existing rust-lightning message implementations?

**Comment by TheBlueMatt** [comment]
Right, I mean for integration we'd probably need to (a) pass all the existing tests/fuzz tests from rust-lightning, (b) use the rust-lightning serialization framework somehow, I guess probably move it to the msgs crate?, (c) drop the derive depends unless there's a good reason it can't be written without them.

**Comment by DR-BoneZ** [comment]
syn and quote are pretty standard crates for writing any kind of derive macro, and they are only used for source code generation as part of the build process, so it shouldn't affect portability if that's a concern. Without them I'd have to reimplement the parser for converting the raw token stream into an abstract syntax tree.

**Comment by DR-BoneZ** [comment]
Also those crates are maintained by a member of the rust internals library team.

**Comment by DR-BoneZ** [comment]
Just ran some benchmarks. For the watchtower init message, this crate cuts down serialization + deserialization time down by about 70% compared to the lnd implementation.

**Comment by ariard** [comment]
That seems cool numbers, what was your benchmark setup ? What watchtower init message are you talking about ?

**Comment by TheBlueMatt** [comment]
Is that vs lnd (in go, so that might be expected), or against the current stuff in rust-lightning?

**Comment by ariard** [comment]
Actually trying to use it to implement [tlv_payload](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#tlv_payload-payload-format)

**Comment by DR-BoneZ** [comment]
It is vs lnd. I don't expect a performance improvement against the current serialization, the main benefit is ergonomics. @ariard I'll push an update to crates.io, and move the repo into this org.

**Comment by DR-BoneZ** [comment]
Nevermind, looks like I'll need to be a member of the org to transfer ownership.

**Comment by TheBlueMatt** [comment]
Hmm, so I took another look at this and it just seems pretty far from integratable - there's a bunch of things (error types, rust-bitcoin hash types, secp signature/key types, etc) we'd need to map, and it looks like mostly the actual message types aren't there, just ways to deserialize TLV. As for TLV deserialization, I think we'd probably go a different route - we shouldn't be allocating at all when deserializing TLVs unless we have to (ie for *actually* variable-length fields).

I'm gonna close this for now, but happy to reopen it if you're interested in working more on this.
