### ISSUE TITLE
Split route calculation from channel rumor message handling

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#432]
We currently have one object that both handles route calculation and receiving gossip messages (to create its routing db). We should split this in two so that its possible to have a remote server provide routing data while still calculating routes locally.

**Comment by naumenkogs** [comment]
@TheBlueMatt trying to pick this up.
Am I correct that we should create something like NetworkGraphMonitor (which implements RoutingMessageHandler).
It than can be used as an argument to Router's function get_route?

Then you can plug-in different routing data providers, etc.

**Comment by naumenkogs** [comment]
@TheBlueMatt please close this one.
