### ISSUE TITLE
ChainWatchInterface incompatible with proposed BIP158 filters

### ISSUE THREAD

**Issue by tamasblummer** [rust-bitcoin/rust-lightning#44]
ChainWatchInterface offers filter by spent outpoint. These are no longer available in proposed BIP158 base filter. Instead only filter by spent script possible. Please change interface otherwise the lightning node will depend on full nodes not using filters.

**Comment by TheBlueMatt** [comment]
Yup, will fix this in the coming days. I'm working on serialization/deserialization stuff on ChannelMonitor, but will hit this afterwards.
