### ISSUE TITLE
Cannot pay an invoice : Failed to find route

### ISSUE THREAD

**Issue by yaslama** [rust-bitcoin/rust-lightning#465]
I opened a channel from rust-lightning to lnd, then generated an invoice in lnd and tried to pay it using the command:
`s lntb1..`
It failed wit the error:
`Failed to find route: Cannot route when there are no outbound routes away from us`

**Comment by TheBlueMatt** [comment]
"Cannot route when there are no outbound routes away from us" <- do you have any channels open? That error implies you have no channels since there are no ways to route outbound away from you.

**Comment by yaslama** [comment]
Sure. There is a channel. At least from rust-lightning POV when using the command `l c`. The peers were also connected as shown by `l p`
BTW, from the lnd side (`lncli listchannels`) the channel was not active.

**Comment by ariard** [comment]
Did enough blocks have been mined on testnet to confirm channel (6 blocks) ?

**Comment by TheBlueMatt** [comment]
Also, IIRC the sample client is pretty dumb - it doesn't bother to reconnect peers that it has a channel open with unless you do so explicitly. However, the [list_usable_channels](https://docs.rs/lightning/0.0.10/lightning/ln/channelmanager/struct.ChannelManager.html#method.list_usable_channels) response which is passed to the router to determine potential next-hops considers whether you are connected, as documented at [is_live](https://docs.rs/lightning/0.0.10/lightning/ln/channelmanager/struct.ChannelDetails.html#structfield.is_live).

**Comment by yaslama** [comment]
@ariard I tried after 26 confirmations and it doesn't help. @TheBlueMatt the command `l p` returns the other peer. I also tried to reconnect explicitly, but it doesn't help. Please notice that from lnd point of view, the channel is shown as not active but `l c` gives no such information.

**Comment by TheBlueMatt** [comment]
Hmm, interesting, well at least it sounds like rust-lightning and lnd *agree* that the channel isn't live (though the sample app doesn't print that)...as to *why*, unclear...If the same app was offline when the channel confirmed, it may be just a case of the sample app not having implemented chain replay on reload. I [pushed a fix to print the is_live value in l c](https://github.com/TheBlueMatt/rust-lightning-bitcoinrpc/commit/a323959b6a290017595a506decd7d9c46a3a8110), but if you missed the block where the channel confirmed you may have to wait until I finish implementing that in the sample client hopefully later this week :)

**Comment by yaslama** [comment]
Thanks @TheBlueMatt, the channel is live when I opened it from lnd (as private). Closing the issue
