### ISSUE TITLE
Store + use channel value pulled from the chain to inform routing

### ISSUE THREAD

**Issue by ariard** [rust-bitcoin/rust-lightning#483]
Right now we store channel announcement independently of the value. We should check it against some user-config value. There is a TODO in  handle_channel_announcement

**Comment by TheBlueMatt** [comment]
I'm not sure what this means? We store it *where*?

**Comment by ariard** [comment]
If utxo has been checked we store this in network.channels, the TODO:  "Check if value is worth storing..."

**Comment by TheBlueMatt** [comment]
Ah, right, yea, so store + use the channel value we pulled off the chain if the user implemented get_chain_utxo.

**Comment by sourabhmarathe** [comment]
I am taking a look at this issue.

**Comment by naumenkogs** [comment]
Oh, I just realized #651 somewhat does this (and probably #646 later).

**Comment by TheBlueMatt** [comment]
Indeed, I believe this has been addressed.
