### ISSUE TITLE
Swap announcement/update serials for block timestamp.

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#493]
We currently just send serials in update/announcement messages as a monotonically increasing number, but other implementations (incorrectly) assume that they are actually timestamps. We should just use the last block timestamp since thats easy to access.

**Comment by ariard** [comment]
Fix BOLT to align node_announcement timestamp encoding on the channel_update one ?

**Comment by TheBlueMatt** [comment]
Are they currently treated differently in the BOLTs? IIRC they are both explicitly allowed to be anything that increases, but are called "timestamp"s and others treat them as timestamps (when they are not).

**Comment by ariard** [comment]
"MUST set timestamp to greater than 0, AND to greater than any previously-sent channel_update for this short_channel_id SHOULD base timestamp on a UNIX timestamp " (channel update)

"MUST set timestamp to be greater than that of any previous node_announcement it has previously created MAY base it on a UNIX timestamp" (node announcement)

So yes a divergence, but more broadly if everyone interpret them as UNIX timestamps it should be mandatory to avoid confusion. Or some kind of semantic like nLocktime to either unix or block height.

**Comment by TheBlueMatt** [comment]
Hmm, interesting. Either way we should get both removed from the spec and clarify that nothing should depend on timestamps being any more accurate than the latest block time (though I don’t know that it makes sense to allow anything as it does now, since efficient graph sync will likely rely on it).

**Comment by jkczyz** [comment]
> Hmm, interesting. Either way we should get both removed from the spec and clarify that nothing should depend on timestamps being any more accurate than the latest block time (though I don’t know that it makes sense to allow anything as it does now, since efficient graph sync will likely rely on it).

Is there an open issue for this in the spec?

**Comment by TheBlueMatt** [comment]
Apparently there is not. I noted what needs to happen on https://github.com/lightningnetwork/lightning-rfc/pull/584#issuecomment-595557571
