### ISSUE TITLE
Architecture Diagrams

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#497]
Our README says our arch description is "coming soon", and, we pretty desperately need one.

**Comment by ariard** [comment]
Like libbitcoin: https://github.com/libbitcoin/libbitcoin-system/wiki ? Do you have in mind something more precise or good examples?

**Comment by jkczyz** [comment]
I'd like to see data flow or sequence diagrams in relation to the system architecture. For instance, how data is received/sent on the wire, how these messages generate events, which entities consume these events, how data is stored in memory or persisted to disk, etc. This would give a better sense of how the system operates than a diagram showing connections between modules.

**Comment by ariard** [comment]
Closed as #516
