### ISSUE TITLE
docs(CONTRIBUTING): add to coding conventions

### ISSUE THREAD

**Issue by maxgiraldo** [rust-bitcoin/rust-lightning#500]
I think it may be helpful to add a few more coding conventions based on rust's style guide, i.e. 100-character line width and indentation level of 4, but I leave it up to you to decide what the actual values should be.

edit: The rationale being that this will help code readability.

Reference: https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md

**Comment by jkczyz** [comment]
Yes, definitely! We're currently ironing out the wrinkles with using rustfmt to enforce this. See #425.

**Comment by maxgiraldo** [comment]
oh I missed that! awesome, good to hear. Will close this then.
