### ISSUE TITLE
ChainListener tests for ChannelManager

### ISSUE THREAD

**Issue by jkczyz** [rust-bitcoin/rust-lightning#531]
Add unit tests demonstrating the `ChainListener` behaviors of `ChannelManager`.

**Comment by galderz** [comment]
Is this still relevant? I see that `ChainListener` was [removed](https://github.com/rust-bitcoin/rust-lightning/commit/1599a13643d893277eb3921c1bb15297547eb030#diff-5aeff0ad041894153ce9f8067da83bb7361810617d9031e8ce5ba4d2ce9dfc0a).

**Comment by jkczyz** [comment]
Indeed... thanks for pointing that out! Closing.
