### ISSUE TITLE
Improve ChannelKeys TODOs

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#567]
We currently have TODOs in public documentation, which isn't OK, but also we should replace the with real documentation before the next release.

**Comment by TheBlueMatt** [comment]
Also, we should probably fix up the APIs to be sensible post-559 pre-0.0.11.

**Comment by ariard** [comment]
We should make signing function as pure function do avoid any side-effect and return a Result<Signature,Error> to propagate back error to caller.

See https://github.com/rust-bitcoin/rust-lightning/pull/559#discussion_r405766208 and https://github.com/rust-bitcoin/rust-lightning/pull/562#discussion_r405758940

**Comment by TheBlueMatt** [comment]
The ChannelKeys stuff should never be pure functions - many cases of channel keys require internal state to enforce that we dont eg sign two different local commitment transactions. They should, of course, return Result<>s, though maybe I misunderstood your point.

**Comment by valentinewallace** [comment]
Should this have been closed by #598?

**Comment by TheBlueMatt** [comment]
Yep!
