### ISSUE TITLE
Update to new rust-bitcoin version & type system

### ISSUE THREAD

**Issue by dr-orlovsky** [rust-bitcoin/rust-lightning#578]
Some time ago I implemented new type system for `rust-bitcoin` hash-based types: <https://github.com/rust-bitcoin/rust-bitcoin/pull/349>. However this was a breaking change and I see that it prevents now `rust-lightining` from following the new releases of `rust-bitcoin`: there is a considerable work associated with adopting new types throughout rust-lightning code. If you ACK the idea, I can work on adoption of the new bitcoin hash types to the library so it may upgrade to the latest version of `rust-bitcoin` dependency.

**Comment by TheBlueMatt** [comment]
Yea, we should absolutely keep up with latest rust-bitcon crate dependencies. The new types upstream are quite nice, no reason we shouldnt use them.
