### ISSUE TITLE
Relicensing MIT + Apache

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#659]
I think it makes sense to re-license RL under both Apache and MIT instead of only Apache, to allow those with Apache license incompatibility or concerns to use it. To do so, we need anyone who's made significant contributions before to sign off. I've listed all of the folks who show up in git shortlog here and it'd be great if everyone could respond indicating that they're happy to dual-license their previous (and future) contributions under MIT as well. If we don't get everyone that may be OK, but we'll need to go back and check that their contributions were relatively minor.

If you're on this list, please respond indicating so with "I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license."

 - [x] @elichai 
 - [x] @murtyjones 
 - [x] @jeandudey 
 - [x] @moneyball 
 - [x] @arik-so 
 - [x] @rloomba 
 - [x] @valentinewallace 
 - [x] @sourabhmarathe 
 - [x] @jkczyz 
 - [x] @neonknight64 
 - [x] @ccdle12 
 - [x] @ariard 
 - [x] @rex4539 
 - [x] @devrandom 
 - [x] @rrybarczyk 
 - [x] @D4nte 
 - [x] @SWvheerden 
 - [x] @naumenkogs 
 - [x] @dr-orlovsky 
 - [x] @sgeisler 
 - [x] @dongcarl 
 - [x] @philipr-za 
 - [x] @stevenroose 
 - [x] @savil 
 - [x] @yuntai 
 - [x] @joemphilips 
 - [ ] @Aleru

**Comment by elichai** [comment]
ACK
Maybe clarify that right now it's licensed Apache 2.0 and you want to add MIT to that as a dual license.
I didn't remember if this repo was Apache or CC0

**Comment by murtyjones** [comment]
I hearby relicense my previous work under MIT in addition to the existing Apache2 license

**Comment by jeandudey** [comment]
ACK, MIT/Apache-2.0 seems better.

**Comment by moneyball** [comment]
ACK

**Comment by arik-so** [comment]
ACK, and I _hereby_ relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by rloomba** [comment]
ACK.

I hearby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by valentinewallace** [comment]
ACK, and I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by sourabhmarathe** [comment]
ACK, and I hereby relicense my previous contributions to rust-lightning
under MIT in addition to the existing Apache2 license.

**Comment by jkczyz** [comment]
ACK. I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by neonknight64** [comment]
ACK, and I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by ccdle12** [comment]
ACK, and I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by ariard** [comment]
ACK, and I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by rex4539** [comment]
ACK

**Comment by devrandom** [comment]
I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by rrybarczyk** [comment]
ACK

I hearby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by sr-gi** [comment]
ACK

**Comment by D4nte** [comment]
"I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license."

**Comment by SWvheerden** [comment]
ACK

**Comment by naumenkogs** [comment]
I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by dr-orlovsky** [comment]
I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by dongcarl** [comment]
I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by philipr-za** [comment]
I hearby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by stevenroose** [comment]
ACK

**Comment by savil** [comment]
I hereby relicense my previous contributions to rust-lightning under MIT in addition to the existing Apache2 license.

cool!

**Comment by yuntai** [comment]
I hereby relicense my previous contributions to
rust-lightning under MIT in addition to the existing Apache2 license.

**Comment by joemphilips** [comment]
ACK
