### ISSUE TITLE
Standalone C++ bindings

### ISSUE THREAD

**Issue by jkczyz** [rust-bitcoin/rust-lightning#677]
Discussed offline. In this variation, the C++ class would be `LDKObject`. Since the copy constructor would be deleted, any object passed to `rust_fn` would need to be an rvalue; it would be a compilation error to pass the object as an lvalue. Instead, the user would need to explicitly `std::move` the lvalue in order to pass it to `rust_fn` as an rvalue, which would trigger the move constructor.

Agreed to open an issue and prioritize based on user need for the C++ header.

_Originally posted by @jkczyz in https://github.com/rust-bitcoin/rust-lightning/pull/618#discussion_r476858142_

**Comment by TheBlueMatt** [comment]
Moved to https://github.com/lightningdevkit/ldk-c-bindings/issues/32
