### ISSUE TITLE
[Peers] Security: Initialize act data buffer with random data

### ISSUE THREAD

**Issue by julianknutsen** [rust-bitcoin/rust-lightning#700]
As a decryption layer, I want to use non-zero initial ciphertext buffers so that chacha failures biasing towards zero aren't masked.

**Definition of Done:**
* Random data is used to fill the initial act buffers
* Optional: Buffers are set to 0 for tests to remove nondeterminism

**Tech Discussion:**

Per [this discussion](https://github.com/arik-so/rust-lightning/pull/2#discussion_r480302102), fill with random data to help reduce masking decryption failures. I don't think the nondeterminism is really an issue for tests, but I've included it since it came up in the discussion.

**Comment by TheBlueMatt** [comment]
We don't have a random source in non-testing modes - we'd have to force the user to provide it, which isn't worth it (or we can just do it in testing). Still, I'm not sure its worth doing something like this - the data is MAC'd, so there should be no difference in "bias" between 0s and random data.

**Comment by ariard** [comment]
Thinking further, initializing act data buffer with randomness to prevent an encryption failure due to poor key randomness is likely circular. Or it would require to ask for a supplemental source of randomness different from the one we're generating keys. 

I concede, finally might not worth it.

**Comment by julianknutsen** [comment]
I've removed this item from the backlog so there aren't any dangling issues. I'm happy to do these one-offs since I literally just fabricated this process yesterday, but if the meta issues are a useful abstraction its probably worth making sure they stay up-to-date.

If not, might be worth finding a way to eliminate them and still get the same information from labels or something else.
