### ISSUE TITLE
Consider changing about and readme text

### ISSUE THREAD

**Issue by casey** [rust-bitcoin/rust-lightning#728]
For users unfamiliar with the project, the about text and readme header, "Rust-Lightning, not Rusty's Lightning!", are somewhat opaque. It might be a good idea to change it to something that gets across the purpose of the project, like "A Low-level Lightning SDK in Rust".

**Comment by valentinewallace** [comment]
I'd support this if you wanna PR it!

**Comment by TheBlueMatt** [comment]
Heh, go for it, but we should still have fun and keep the old joke somewhere (maybe link to c-lightning) :)

**Comment by casey** [comment]
I just opened #729, I don't have access to the about box so that would have to be changed by someone with admin access. I wasn't sure where to put the old joke, but please feel free to push it to this PR branch  😄
