### ISSUE TITLE
NodeJS C Bindings Pointer Returns

### ISSUE THREAD

**Issue by arik-so** [rust-bitcoin/rust-lightning#747]
We should add a flag to some exposed C methods to indicate the addition of one level of indirection to the return type. That is, instead of the method looking like

```rust
pub extern "C" fn ffi_method(…) -> crate::ReturnType {
    …
    local_ret
}
```

it should instead be generated to look thus:

```rust
pub extern "C" fn ffi_method(…) -> *const crate::ReturnType {
    …
    Box::into_raw(Box::new(local_ret))
}
```

There are literally just five methods that need this change right now, but adding such a flag to the generator will drastically simplify NodeJS automation in the future.

**Comment by TheBlueMatt** [comment]
Looks like we're going a different way with JS (via WASM and our own wrapper instead of wasm_bindingen), so I dont think this is relevant anymore.
