### ISSUE TITLE
ChannelManager::force_close_channel does not fail on random channel_id

### ISSUE THREAD

**Issue by sr-gi** [rust-bitcoin/rust-lightning#773]
`ChannelManager::force_close_channel` attempts to close any given `channel_id`, even if the latter is unknown by the manager.

This contrasts with `ChannelManager::close_channel`, where a `errors::APIError::ChannelUnavailable` will be raised.

Having the same interface regarding unknown channels by both methods feels like the way to go, so I think `force_close_channel` should be updated.

**Comment by sr-gi** [comment]
I can tackle this issue if there's consensus on the update btw.

**Comment by TheBlueMatt** [comment]
> I can tackle this issue if there's consensus on the update btw.

I'd say go for it.
