### ISSUE TITLE
Implement BOLT2: `opt_shutdown_anysegwit`

### ISSUE THREAD

**Issue by ariard** [rust-bitcoin/rust-lightning#780]
See https://github.com/lightningnetwork/lightning-rfc/pull/672.

**Comment by TheBlueMatt** [comment]
We should probably do a few things related to this - we should (a) implement the protocol itself, (b) we should require the feature for all peers, (c) we should change KeysInterface.get_shutdown_pubkey to allow it to return any segwit script, probably via a segwit type enum or so.

**Comment by ariard** [comment]
Closed by #794
