### ISSUE TITLE
Derive Debug for MessageSendEvent

### ISSUE THREAD

**Issue by galderz** [rust-bitcoin/rust-lightning#796]
`MessageSendEvent` enum should derive `Debug`, to make it easy for users to see which events are pending in the `ChannelManager`. Without that enum, the only way to figure out which event you're handling is by pattern matching on all possible types, which are close to 20.

**Comment by galderz** [comment]
See [Slack discussion](https://lightningdevkit.slack.com/archives/CTBLT3CAU/p1613046066213700).

**Comment by duncandean** [comment]
This is closed by #846

**Comment by ariard** [comment]
Good point, closing
