### ISSUE TITLE
ChainInterface is easy to misuse

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#80]
In writing https://github.com/TheBlueMatt/rust-lightning-bitcoinrpc I almost misused ChainWatchInterface, almost calling ChannelManager::block_connected and PeerHandler::block_connected instead of only calling ChainWatchInterfaceUtil::block_connected (which will call the others for you).

I'm not actually sure what a better interface looks like. I played around a bit with making some things pub(crate) in chaininterface but couldn't come up with anything I actually liked, sadly.

**Comment by dongcarl** [comment]
>  I played around a bit with making some things pub(crate) in chaininterface but couldn't come up with anything I actually liked, sadly.

What was insufficient with `pub(crate)`?

**Comment by TheBlueMatt** [comment]
We don't have a ChainWatchInterfaceUtil anymore, and this interface is much much harder to mis-use now.
