### ISSUE TITLE
Implement Lightning message signing

### ISSUE THREAD

**Issue by sr-gi** [rust-bitcoin/rust-lightning#843]
Both `lnd` and `c-lightning` do implement a "Lightning Message Signing" protocol to allow nodes to sign/verify messages from other nodes.

The signature format is as described in https://twitter.com/rusty_twit/status/1182102005914800128

```
zbase32(SigRec(SHA256(SHA256("Lightning Signed Message:" + msg))))
zbase32 from https://philzimmermann.com/docs/human-oriented-base-32-encoding.txt 
SigRec has first byte 31 + recovery id, followed by 64 byte sig. 
```

It may make sense to add zbase32 to LDK so the signature algo can be implemented, or even implement it within LDK and add bindings.

**Comment by sr-gi** [comment]
I implemented this for The Eye of Satoshi a while back, so I can take care to port it to Rust if you think it makes sense to have it here.

**Comment by TheBlueMatt** [comment]
Sure, if you feel so inclined, go for it!
