### ISSUE TITLE
Allow multi-hop route hints

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#945]
Invoices can contain multiple hops from a public node to get to the target, but our router currently only can handle single-hop hints. Worse, this limitation is captured in the API, making the invoice -> get_route API really hard to use.

**Comment by TheBlueMatt** [comment]
Untagging Jeff since the important part is done.

**Comment by jkczyz** [comment]
@abhik-99 will work on this issue.
