### ISSUE TITLE
Include total fee paid in `PaymentSent`

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-lightning#999]
Also `payment_hash` while we're at it, cause why not.

**Comment by TheBlueMatt** [comment]
Also we should put it in the return value from `get_route`, maybe we create a wrapper that's just "GetRouteReturnValue" or something that has metadata about the route plus the route itself.

**Comment by valentinewallace** [comment]
Assigned to @galderz :) thank you!

**Comment by TheBlueMatt** [comment]
Closed in #0163.
